### ISSUE TITLE
[Request] Update to 1.0 item list

### ISSUE THREAD

**Issue by Shadowfury22** [INSYG/CCSaveEdit#1]
It would be great if the save editor recognized the new items (and fixed a couple of mislabeled ones that got updated).

**Comment by YoYoK3nny** [comment]
A workaround is to replace the "itemj.js" file with the "assets/data/item-database.json" from the game. Just be sure to add the following code to the very start of the file after the replace:

`var itemj = `

**Comment by Shadowfury22** [comment]
I'm afraid that's not all that is needed to work with newer save files.
At the beginning of my 1.0 playthrough, this editor was able to load my item list. But after progressing in the game, it suddenly stopped working. Currently I'm not able to get the "loaded save" confirmation message after putting in my encrypted string, even though I can still get the player, decrypted and spaced tabs working. The inventory one doesn't work :(

**Comment by Shadowfury22** [comment]
Thank you, that worked like a charm!
